version: 0.0.{build}
image: Visual Studio 2017
configuration: Release
platform:
- x64
build:
  verbosity: minimal
test:
  # only assemblies to test
  assemblies:
    only:
      - 'Release\InterpreterTests.dll'
artifacts:
- path: shootpp.7z
  name: Shoot++