version: 0.0.{build}
image: Visual Studio 2017
configuration: Release
platform:
- x64
build:
  verbosity: minimal
test:
    - 'InterpreterTests\InterpreterTests.dll'
artifacts:
- path: shootpp.zip
  name: Shoot++